name: Anthropocene
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22398
title: Designing the future as if people mattered
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#1f1f1f'
    - '#bcc3c9'
    - '#72819c'
    - '#d29568'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: engagement
    item: 857a0c08-30f4-487c-8b0c-4cf15952b9c7
    url: null
